# -*- coding: utf-8 -*-
"""Analise_Estatistica_Apresentacao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/KepryDeSousa/SISAB_CNES_Ceara_Macico_de_Baturite/blob/main/Analise_Estatistica_Apresentacao.ipynb

# Previne Brasil: Analise do Indicador de 2020

### Banco. BD
"""

Bd = files.upload()

files.upload()

"""### Bibiliotecas Iniciais

"""

import numpy as np
import pandas as pd
!pip install plotly 
import plotly.express as px
from google.colab import files

Banco_Indicadores = pd.read_excel("Analise_Dados.xlsx")
Relacao =  pd.read_excel("TCC - Relação de UAPS.xlsx")

Relacao = Relacao.replace(np.NaN,0)

Acarape = Banco_Indicadores.loc[Banco_Indicadores["Municipio"] == "Acarape"]

"""## Variavel dependente VS Independente:
As variáveis dependentes e independentes são dois tipos de variáveis usadas em análises estatísticas para entender a relação entre elas.  

* Independente
>  é usada para prever ou explicar a variação na variável dependente. É também chamada de variável explicativa ou preditora.

* Dependente: 
> dependente é a variável que é afetada ou medida como resultado da mudança na variável independente.

## Indicador I : Determinação de dados

Note que se usassemos apenas uma Cidade a concentração de dados dela não traria um bom resultado, ja que possuiriamos apenas 3 dados por indicador p/ ano, com a sua soma total por cidade nos ultimos 3 anos seria de apenas 9 dados, o que não parece nescessitar de uma analise, ja que o mesmo é passivo de visualização;

---



 considerar a Microrregião de Baturité como uma unidade torna a analise mais eficiente
"""

Indicadores_I = Banco_Indicadores.loc[Banco_Indicadores["Indicador"] == 1]
I_1 = Indicadores_I[["Municipio","Indicador","Q1_2020","Q2_2020","Q3_2020"]]
I_1

"""### Indicador_I 2020
> Levando em consideração todo o Maciço no intervalo de um ano

### codes
"""

I = Indicadores_I[["Municipio","Indicador","Q1_2020","Q2_2020","Q3_2020","Q1_2021","Q2_2021","Q3_2021","Q1_2022","Q2_2022","Q3_2022"]]
Media = I[["Q1_2020","Q2_2020","Q3_2020"]].mean()
I['Media_Ano_2020'] = Media.mean()

"""### Analise Descritiva : """

# agora possuiemos 3 dados por ano X 13 (quantidade de Municipios)
grafico = px.scatter(I, x="Municipio",y=["Q1_2020","Q2_2020","Q3_2020","Media_Ano_2020"],       
           )
grafico.update_traces(marker = dict(size = 15, line=dict(width = 4)), selector = dict(mode = 'markers'))

"""São utilizadas para indicar o grau de variação dos elementos de um conjunto numérico em relação à sua média."""

grafico = px.line(I, x="Municipio",y=["Q1_2020","Q2_2020","Q3_2020","Media_Ano_2020"],title="Baturité Indicador I - 2020")
grafico.update_traces(mode='lines+markers', marker_line_width=2, marker_size=10)

"""são usadas para representar grandes quantidades de dados que ocorrem em um período de tempo contínuo."""

px.histogram(I, x=["Q1_2020","Q2_2020","Q3_2020","Q1_2021","Q2_2021","Q3_2021","Q1_2022","Q2_2022","Q3_2022"], nbins=20)

"""O histograma é uma ferramenta da qualidade muito importante para análises estatísticas. É um gráfico que mostra a distribuição de acontecimentos registrados em todo o espectro.

### Outros Meios da descrição:
"""

import statistics as stats

#moda
moda1 = stats.mode(I["Q1_2020"])
moda2 = stats.mode(I["Q2_2020"])
moda3 = stats.mode(I["Q3_2020"])


media = I[["Q1_2020","Q2_2020","Q3_2020"]].mean()
mediana =I[["Q1_2020","Q2_2020","Q3_2020"]].median()

print(f"Media dos Quadrimestres [1,2,3]_Ano 2020:\n{media}\n\n"
     +f"Mediana dos Quadrimestres [1,2,3]_Ano 2020:\n{mediana}\n"
     +f"\nModa dos Quadrimestres [1]_Ano 2020:\n{moda1}"
     +f"\nModa dos Quadrimestres [2]_Ano 2020:\n{moda2}"
     +f"\nModa dos Quadrimestres [3]_Ano 2020:\n{moda3}"

      )

#Variancia vs Desvio padrão 
variancia  = np.var(I["Q1_2020"])
desvio_Padrao = np.std(I["Q1_2020"])
Amplitude = np.max(I["Q1_2020"]) - np.min(I['Q1_2020'])
# variancia = soma((xi - media)²) / (n - 1)
# desvio_padrao = raiz(variancia)

print(f"Variancia: {variancia}\nDesvio Padrão:{desvio_Padrao}"
      f"\n{I['Q1_2020']}"
      f"\nAmplitude: {Amplitude}")

"""## Porque Usa-los ?:
>A variância e o desvio padrão são medidas de dispersão que indicam o quão distantes os dados estão da média.



---


>A amplitude é uma medida de dispersão que indica a diferença entre o maior e o menor valor em um conjunto de dados.

### Alternativas Cabiveis de uma analise qualitativa (Mais Robusta)
  > Um dado qualitativo é uma informação que descreve uma característica ou uma qualidade de um objeto ou evento



---



* Analisar efeitos climaticos **Vs** Quantidade de Atendimentos.
> Nescessita de dados climaticos coesos Vs Localizações

* Analise fluxo de atendimentos por UAPS
> nescessita de dados geometricos das Unidades
> 
>Assim teriamos a relevancia da Unidade para sua cidade

* Desenvolvimento de uma API conectada ao sistema do Programa Previne Brasil, afim de comparar dados de cidades do interior do Ceará com a mesmas se não parecidas em caracteristicas
> Django **Vs** Flask :
> 
> Bibliotecas Python para desenvolver uma aplicação web afim de coletar o maximo de dados possiveis em menos tempo
>
> Talvez tenha a nescessidade de uma solicitação de acesso
"""